### ISSUE TITLE
question about axi_ram

### ISSUE THREAD

**Issue by yhw1993** [alexforencich/verilog-axi#5] opened 2019-11-24 12:44 UTC
Dear Alex,
I have a question about the module of axi_ram. When you use "initial begin end " to initialize the mem[(2**VALID_ADDR_WIDTH)-1:0], should you use "VALID_ADDR_WIDTH" instead of "ADDR_WIDTH"? The attached files is more explicit. I am looking forward to your answer.Thanks!
![1574171937(1)](https://user-images.githubusercontent.com/33685159/69494829-234c3b00-0efb-11ea-90b7-050c2be5b047.jpg)

**Comment by alexforencich** [comment] 2019-11-24 23:39
duplicate of #4

**Closed by alexforencich** 2019-11-24 23:39 UTC
Labels: duplicate
